{***************************************************************************
               Copyright (c) PilotLogic Software House
                       All rights reserved
 
   MagicScript TOTAL Registration file for Library: Graphics32
   Generated by MagicScript LibraryBuilder 7.0
   Create at : 7/10/2019 7:30:21
   This file is part of CodeTyphon Studio (https://www.pilotlogic.com/)
 ***************************************************************************}
 
Unit ms_allreg_Graphics32;
 
 Interface
 
 Uses
  GR32,
  GR32_ColorSwatch,
  GR32_Image,

  msrtti_GR32,
  msrtti_GR32_ColorSwatch,
  msrtti_GR32_Image;
 
Implementation
end.
 
{***********************************************************************

 //.............. $$$_MissUnits ..........................
Classes
Controls
GR32_AllStrings
Graphics
IntfGraphics
LCLIntf
LCLType
SysUtils
Types
Forms
GR32_Backends
GR32_Blend
GR32_Containers
GR32_Math
GR32_VectorUtils
LMessages
Math
GR32_Layers
GR32_MicroTiles
GR32_RangeBars
GR32_RepaintOpt
GR32_XPThemes
TypInfo
//.............. $$$_BadConsts ..........................
0
//.............. $$$_BadTypes ..........................
40
PArrayOfArrayOfCardinal
PArrayOfArrayOfFixed
PArrayOfArrayOfFixedPoint
PArrayOfArrayOfFloatPoint
PArrayOfArrayOfInteger
PArrayOfArrayOfPoint
PArrayOfByte
PArrayOfCardinal
PArrayOfFixed
PArrayOfFixedPoint
PArrayOfFloat
PArrayOfFloatPoint
PArrayOfInteger
PArrayOfPoint
PArrayOfSingle
PArrayOfWord
PByteArray
PCardinalArray
PColor32
PColor32Array
PColor32Entry
PColor32EntryArray
PFixed
PFixedArray
PFixedPoint
PFixedPointArray
PFixedRec
PFixedRect
PFloat
PFloatArray
PFloatPoint
PFloatPointArray
PFloatRect
PIntegerArray
PPalette32
PPoint
PPointArray
PSingleArray
PWordArray
TSize
//.............. $$$_BadVars ..........................
0
//.............. $$$_BadCIOs ..........................
0
//.............. $$$_BadFunProcs ..........................
0
 //.............. $$$_FilesUsed ..........................
3
C:\codetyphon\typhon\components\pl_Graphics32\source\GR32.pas
C:\codetyphon\typhon\components\pl_Graphics32\source\GR32_Image.pas
C:\codetyphon\typhon\components\pl_Graphics32\source\GR32_ColorSwatch.pas

 ***********************************************************************}
